Auth pages
git-0r/ecom_screens pull request #5
Opened 2022-02-20 19:33 UTC by git-0r

# Created ecom auth screens
# 1. Login
![ecom7](https://user-images.githubusercontent.com/68228131/154860715-d8154135-2479-48a0-a8ea-a1d2ef717afd.png)
# 2. Log out
![ecom8](https://user-images.githubusercontent.com/68228131/154860727-c3f9bd09-d441-4bf5-8e61-d5a5853c7bfc.png)
# 3. Signup
![ecom9](https://user-images.githubusercontent.com/68228131/154860734-037bc72b-cc89-4155-943e-0b11e2646830.png)

2022-02-20 22:41 UTC, manish-GH approved these changes
The UI is awesome and responsive too, Nice work. 

Replace px with rem and em wherever mentioned and you are good to merge

2022-02-20 22:41 UTC, manish-GH commented on css/cart_page.css
> +  max-width: 1440px;
use rem

2022-02-20 22:41 UTC, manish-GH commented on css/cart_page.css
> +  max-height: 60px;
use rem

2022-02-20 22:41 UTC, manish-GH commented on css/cart_page.css
> +  height: 400px;
use rem

2022-02-20 22:41 UTC, manish-GH commented on css/cart_page.css
> +@media screen and (max-width: 600px) {
use em for media queries

2022-02-20 22:41 UTC, manish-GH commented on css/listing_page.css
> +  max-width: 1440px;
use rem

2022-02-20 22:41 UTC, manish-GH commented on css/listing_page.css
> +  max-height: 60px;
use rem

2022-02-20 22:41 UTC, manish-GH commented on css/listing_page.css
> +  height: 400px;
use rem

2022-02-20 22:41 UTC, manish-GH commented on css/listing_page.css
> +@media screen and (max-width: 600px) {
use em

2022-02-20 22:41 UTC, manish-GH commented on css/login_page.css
> +  max-width: 1440px;
use rem

2022-02-20 22:41 UTC, manish-GH commented on css/login_page.css
> +  max-height: 60px;
use rem

2022-02-20 22:41 UTC, manish-GH commented on css/logout_page.css
> +  max-width: 1440px;
use rem

2022-02-20 22:41 UTC, manish-GH commented on css/logout_page.css
> +  max-height: 60px;
use rem

2022-02-20 22:41 UTC, manish-GH commented on css/logout_page.css
> +@media screen and (max-width: 600px) {
use em

2022-02-20 22:41 UTC, manish-GH commented on css/signup_page.css
> +  max-width: 1440px;
use rem

2022-02-20 22:41 UTC, manish-GH commented on css/signup_page.css
> +  max-height: 60px;
use rem

2022-02-20 22:41 UTC, manish-GH commented on css/signup_page.css
> +@media screen and (max-width: 600px) {
use em

2022-02-20 22:41 UTC, manish-GH commented on css/wishlist_page.css
> +  max-width: 1440px;
use rem

2022-02-20 22:41 UTC, manish-GH commented on css/wishlist_page.css
> +  max-height: 60px;
use rem

2022-02-20 22:41 UTC, manish-GH commented on css/wishlist_page.css
> +  height: 400px;
use rem

2022-02-20 22:41 UTC, manish-GH commented on css/wishlist_page.css
> +@media screen and (max-width: 600px) {
use em

2022-02-20 22:41 UTC, manish-GH commented on index.css
> +  max-width: 1440px;
use rem

2022-02-20 22:41 UTC, manish-GH commented on index.css
> +  max-height: 60px;
use rem

2022-02-20 22:41 UTC, manish-GH commented on index.css
> +  height: 400px;
use rem

2022-02-20 22:41 UTC, manish-GH commented on index.css
> +@media screen and (max-width: 600px) {
use em

2022-02-20 22:41 UTC, manish-GH commented on pages/login_page.html
> +            <button class="btn btn-primary login-btn">Submit</button>
replace Submit with Login

2022-02-21 13:57 UTC, Naman-Saxena1 requested changes

2022-02-21 13:57 UTC, Naman-Saxena1 commented on pages/login_page.html
> +                <p class="text-sm">forgot password?</p>
Forgot password as link would be better

2022-02-21 14:36 UTC, Sahil25061999 approved these changes
same suggestion as manish, rest looks good to me, can be merged after doing the changes.

2022-02-21 14:36 UTC, Sahil25061999 commented on pages/login_page.html
> +                <p class="text-sm">forgot password?</p>
use link for forgot password

2022-02-21 17:46 UTC, merged